msm: mhi_dev: Fix compilation errors with mhi snapshot
Fix compiliation errors with mhi snapshot taken from 5.15.c1.
Include the missing dependent header file.

Following are the errors from mhi_uci.c & mhi.h

1. error: use of undeclared identifier 'class_create'

        uci_ctxt.mhi_uci_class = class_create(DEVICE_NAME);
	                                 ^~~~~~~~~~~~

2. incompatible function pointer types assigning to 'int (*)(struct
   device *, struct kobj_uevent_env *)' from 'int (const struct
   device *, struct kobj_uevent_env *)

	uci_ctxt.mhi_uci_class->dev_uevent = mhi_state_uevent;
                                            ^ ~~~~~~~~~~~~~~~~

3. mhi.h:10:10: fatal error: 'linux/mhi_dma.h' file not found.

Change-Id: I09fc49cfa034bc353272fba195c51953f82b302d
Signed-off-by: Veerabhadrarao Badiganti <vbadigan@qti.qualcomm.com>